pohovor/src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 * @ORM\Table(name="books")
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $count;

    /**
     * @ORM\Column(type="integer")
     */
    private $actual_count;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getActualCount(): ?int
    {
        return $this->actual_count;
    }

    public function setActualCount(int $actual_count): self
    {
        $this->actual_count = $actual_count;

        return $this;
    }
}

pohovor/src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',null,array('label'=>'Názov'))
            ->add('author',null,array('label'=>'Autor'))
            ->add('count',null,array('label'=>'Počet'))
            ->add('save',SubmitType::class,[
                'label' => 'Pridať knihu',
                'attr' => [
                    'class' => 'btn btn-lg btn-primary'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

pohovor/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\User;
use App\Form\BookPlusType;
use App\Form\BookType;
use App\Form\UserType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @Route("/book", name="book.")
 */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @param BookRepository $bookRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(BookRepository $bookRepository)
    {
        $books = $bookRepository->findAll();
        return $this->render('book/index.html.twig', [
            'books' => $books
        ]);
    }

    /**
     * @Route("/add", name="add")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function addBook(Request $request)
    {
        $book = new Book();

        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $book->setActualCount($book->getCount());

            $em->persist($book);
            $em->flush();

            $this->addFlash('deleted', 'Kniha bol úspešne pridaná');

            return $this->redirect($this->generateUrl('book.index'));
        }

        return $this->render('book/add.html.twig',[
            'form' => $form->createView()
        ]);


    }

    /**
     * @Route("/delete/{id}", name="delete")
     * @param Book $book
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */

    public function removeBook(Book $book){
        $em = $this->getDoctrine()->getManager();
        $em->remove($book);
        $em->flush();

        $this->addFlash('deleted','Kniha bola úspešne vymazaná');
        return $this->redirect($this->generateUrl('book.index'));
    }

    /**
     * @Route("/add/{id}", name="addmore")
     * @param Request $request
     */

    public function addSpecificBook(Request $request, $id){
        $book = new Book();
        $book = $this->getDoctrine()->getRepository(Book::class)->find($id);
        $oldCount = $book->getCount();

        $form = $this->createForm(BookPlusType::class, $book);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $newCount = $book->getCount();
            $book->setActualCount($book->getActualCount()+$newCount);
            $book->setCount($oldCount+$newCount);
            $em->flush();

            return $this->redirect($this->generateUrl('book.index'));
        }

        return $this->render('book/add2.html.twig',[
            'form' => $form->createView()
        ]);

    }
}

pohovor/templates/book/add.html.twig
{% extends('base.html.twig') %}

{% block body %}

    <h1 style="margin-top: 5vh">Pridať knihu</h1>
    {{ form(form) }}

{% endblock %}

pohovor/templates/book/add2.html.twig
{% extends('base.html.twig') %}

{% block body %}

    <h1 style="margin-top: 5vh">Pridať kusy</h1>
    {{ form(form) }}

{% endblock %}

pohovor/templates/book/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {% for message in app.flashes('deleted') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <div class="row" style="margin-top: 5vh;">

        <h1><i class="fas fa-book-open"></i> Zoznam kníh</h1>
        <a title="Pridať knihu" href="{{ path('book.add') }}" class="btn btn-primary ml-auto" style="">
            <i class="fas fa-plus"></i>
        </a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Názov</th>
            <th>Autor</th>
            <th>Počet</th>
            <th>Aktuálny počet</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}

            <tr>
                <td>{{ book.name }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.count }}</td>
                <td>{{ book.actualCount }}</td>
                <td class="float-right">
                    <a title="Pridať dalšie kusy" href="{{ path('book.addmore',{id: book.id}) }}" class="btn btn-success">
                        <i class="fas fa-plus-circle"></i>
                    </a>
                    <a title="Vymazať knihu" href="{{ path('book.delete',{id: book.id}) }}" class="btn btn-danger">
                        <i class="fas fa-user-minus"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}