pohovor/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="integer")
     */
    private $book_count;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBookCount(): ?int
    {
        return $this->book_count;
    }

    public function setBookCount(int $book_count): self
    {
        $this->book_count = $book_count;

        return $this;
    }
}

pohovor/templates/taken/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}



    <div class="row" style="margin-top: 5vh;">

        <h1><i class="fas fa-user"></i> Čitateľ: {{ user.name }}</h1>
    </div>

    <hr>
    <div class="row">
        <h2 class="text-muted">Vypožičané knihy</h2>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Názov</th>
                <th>Autor</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}

                <tr>
                    <td>{{ book.name }}</td>
                    <td>{{ book.author }}</td>
                    <td class="float-right">
                        <a title="Vrátiť knihu" href="{{ path('taken.back',{user_id: user.id, book_id: book.id}) }}"  class="btn btn-info">
                            <i class="fas fa-hand-point-left"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    {% if user.bookCount<5 %}
    <div class="row">
        <h2 class="text-muted">Nevypožičané knihy</h2>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Názov</th>
                <th>Autor</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for notTakenBook in notTakenBooks %}

                <tr>
                    <td>{{ notTakenBook.name }}</td>
                    <td>{{ notTakenBook.author }}</td>
                    <td class="float-right">
                        <a title="Vypožičať knihu" href="{{ path('taken.take',{user_id: user.id, book_id: notTakenBook.id}) }}" class="btn btn-success">
                            <i class="fas fa-plus-circle"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <div class="row">
            <p class="text-danger">Čitateľ má vypožičaný maximálny počet kníh</p>
        </div>
    {% endif%}
{% endblock %}